### ISSUE TITLE
Add docker annotations

### ISSUE THREAD

**Issue by AlexanderBrevig** [entur/gha-docker#79]
Needs at least `repo_name` and `sha`.

Thanks @EnturWilhelm

**Comment by EnturWilhelm** [comment]
The docker/metadata-action already generates annotations following the opencontainer spec with this data.
The[ following command](https://github.com/entur/gha-docker/blob/main/.github/workflows/push.yml#L159) needs to be updated to use the annotations from the[ following meta action](https://github.com/entur/gha-docker/blob/main/.github/workflows/push.yml#L125).

**Comment by Glenn-Terjesen** [comment]
@EnturWilhelm not supported by Harness, we have the code ready but it was decided to wait.
Closing
