### ISSUE TITLE
Add input flag for push on build

### ISSUE THREAD

**Issue by Glenn-Terjesen** [entur/gha-docker#80]
Depending on the pipeline, some teams would want to upload directly after building,
A input flag to push would solve this.

**Comment by AlexanderBrevig** [comment]
I _think_ simply running `push` without an artifact should do the trick?

**Comment by AlexanderBrevig** [comment]
Futhermore, it is likely that it will be mandatory to do an image scan before push so I don't think this feature would be welcome :/

**Comment by Glenn-Terjesen** [comment]
Security req, closing issue
