### ISSUE TITLE
Check if environment actually exist, if not give a good error message

### ISSUE THREAD

**Issue by Glenn-Terjesen** [entur/gha-docker#82]
![image](https://github.com/entur/gha-docker/assets/48587132/e5b42daf-9ab6-4e22-8475-fd88689d3f52)

PRD env does not exist.
Possible fix: check if secrets is set before continuing.

**Comment by AlexanderBrevig** [comment]
Probably should change 
https://github.com/entur/gha-docker/blob/1d714c9bfe236d7705a304e5a6bab7f897633b97/.github/workflows/push.yml#L10-L11
to use `type: environment`

**Comment by Glenn-Terjesen** [comment]
As we are about to remove the environment property from this repo this is no longer needed.
